//1.local     - scope of local varible are within function only...
//2.instance  - within class but outside method...
//3.static    -within class but outside the method,cannot be local...

public class varibles {
    int z=30;                     //instance ...
    static int c=40;             //static ...
    public static void main (String args[]){
        int a=10;                //local ...
        a=20;
        System.out.println(a+c);
    }
    void display() {
        int a = 20;                //local...
        System.out.println(a);
        System.out.println(c);
        System.out.println(z);
    }
}
